import json
import os
import stat
import subprocess
import tarfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PACKAGE_JSON = ROOT / "package.json"


def run(cmd, cwd=ROOT, env=None):
    merged = os.environ.copy()
    if env:
        merged.update(env)
    return subprocess.run(
        cmd,
        cwd=cwd,
        env=merged,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )


def test_package_json_exposes_dog_cli_without_install_scripts():
    pkg = json.loads(PACKAGE_JSON.read_text(encoding="utf-8"))

    assert pkg["name"] == "@wjira/claude-watchdog"
    assert pkg["bin"] == {"dog": "bin/dog"}
    assert "preinstall" not in pkg.get("scripts", {})
    assert "postinstall" not in pkg.get("scripts", {})
    assert pkg["files"] == [
        "bin/",
        "!bin/__pycache__/",
        "!**/*.pyc",
        "config/",
        "systemd/",
        "install.sh",
        "README.md",
        "docs/",
        "SECURITY.md",
        "LICENSE",
    ]


def test_npm_setup_installer_uses_shim_instead_of_copying_stale_dog():
    text = (ROOT / "install.sh").read_text(encoding="utf-8")
    assert "NPM_PACKAGE_INSTALL=0" in text
    assert "*/node_modules/@wjira/claude-watchdog) NPM_PACKAGE_INSTALL=1 ;;" in text
    assert "install_npm_bin_shim" in text
    assert "installed ~/bin shims to delegate to the npm package CLI" in text


def test_npm_pack_contains_runtime_assets_and_no_runtime_state(tmp_path):
    result = run(["npm", "pack", "--json", "--pack-destination", str(tmp_path)])
    pack_info = json.loads(result.stdout)[0]
    tarball = tmp_path / pack_info["filename"]

    with tarfile.open(tarball) as tf:
        names = set(tf.getnames())

    required = {
        "package/package.json",
        "package/bin/dog",
        "package/bin/claude-tele",
        "package/bin/claude-tele-watchdog",
        "package/install.sh",
        "package/systemd/user/telegram-claude.service",
        "package/systemd/user/telegram-claude-watchdog.service",
        "package/config/env.example",
        "package/config/access.example.json",
    }
    assert required <= names

    forbidden_suffixes = (
        ".env",
        ".token.enc",
        ".token.key",
        ".pyc",
        "access.json",
        "inbound-journal.jsonl",
        "replayed-inbound.jsonl",
    )
    assert not any(name.endswith(forbidden_suffixes) for name in names)
    assert not any("__pycache__" in name for name in names)


def test_npm_installed_setup_finds_packaged_installer_through_bin_symlink(tmp_path):
    pack_result = run(["npm", "pack", "--json", "--pack-destination", str(tmp_path)])
    pack_info = json.loads(pack_result.stdout)[0]
    prefix = tmp_path / "prefix"
    home = tmp_path / "home"
    fake_bin = tmp_path / "fake-bin"
    fake_bin.mkdir()
    home.mkdir()

    run([
        "npm",
        "install",
        "-g",
        "--prefix",
        str(prefix),
        str(tmp_path / pack_info["filename"]),
        "--ignore-scripts",
    ])

    for name, body in {
        "claude": "#!/bin/sh\nexit 0\n",
        "systemctl": "#!/bin/sh\nexit 0\n",
        "loginctl": "#!/bin/sh\nexit 0\n",
        "tmux": "#!/bin/sh\n[ \"$1\" = \"has-session\" ] && exit 1\nexit 0\n",
        "bun": "#!/bin/sh\n[ \"$1\" = \"--version\" ] && echo 1.3.14\nexit 0\n",
    }.items():
        path = fake_bin / name
        path.write_text(body, encoding="utf-8")
        path.chmod(path.stat().st_mode | stat.S_IXUSR)

    (home / ".claude").mkdir()
    (home / ".claude" / ".credentials.json").write_text("{}\n", encoding="utf-8")
    (home / "bin").mkdir()
    (home / "bin" / "dog").write_text("#!/bin/sh\necho stale-home-dog\n", encoding="utf-8")
    (home / "bin" / "dog").chmod(0o700)
    (home / "bin" / "claude-tele").write_text("#!/bin/sh\necho stale-home-engine\n", encoding="utf-8")
    (home / "bin" / "claude-tele").chmod(0o700)
    env = {
        "HOME": str(home),
        "PATH": f"{fake_bin}:{prefix / 'bin'}:{os.environ['PATH']}",
        "USER": "watchdogtest",
    }
    setup_input = "123456:abcdefghijklmnopqrstuvwxyz\nN\n111222333\n1\nn\nn\nn\n"
    result = subprocess.run(
        [str(prefix / "bin" / "dog"), "setup", "--plain"],
        cwd=tmp_path,
        env={**os.environ, **env},
        input=setup_input,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )

    combined = result.stdout + result.stderr
    assert "installer assets not found" not in combined
    assert "installed ~/bin shims to delegate to the npm package CLI" in combined
    assert (home / "bin" / "claude-tele").exists()
    dog_shim = home / "bin" / "dog"
    assert dog_shim.exists()
    assert "Generated by claude-watchdog setup" in dog_shim.read_text(encoding="utf-8")
    engine_shim = home / "bin" / "claude-tele"
    assert "Generated by claude-watchdog setup" in engine_shim.read_text(encoding="utf-8")
    assert "stale-home-engine" not in engine_shim.read_text(encoding="utf-8")
    shim_help = subprocess.run(
        [str(dog_shim), "help"],
        cwd=tmp_path,
        env={**os.environ, **env},
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    assert "Usage: dog <command>" in shim_help.stdout
    shadow_env = {**os.environ, **env, "PATH": f"{home / 'bin'}:{env['PATH']}"}
    path_shadow_help = subprocess.run(
        ["dog", "help"],
        cwd=tmp_path,
        env=shadow_env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    assert "Usage: dog <command>" in path_shadow_help.stdout
    assert "stale-home-dog" not in path_shadow_help.stdout

    path_shadow_status = subprocess.run(
        ["dog", "status"],
        cwd=tmp_path,
        env=shadow_env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    assert "claude-tele status" in path_shadow_status.stdout
    assert "stale-home-engine" not in path_shadow_status.stdout
    assert (home / ".config" / "systemd" / "user" / "telegram-claude.service").exists()
    installed_service = (home / ".config" / "systemd" / "user" / "telegram-claude.service").read_text(encoding="utf-8")
    installed_watchdog = (home / ".config" / "systemd" / "user" / "telegram-claude-watchdog.service").read_text(encoding="utf-8")
    package_root = prefix / "lib" / "node_modules" / "@wjira" / "claude-watchdog"
    assert f"BindReadOnlyPaths={package_root}" in installed_service
    assert f"BindReadOnlyPaths={package_root}" in installed_watchdog
    assert "[claude-watchdog] installed" in combined
